# Generated by Django 4.2 on 2026-05-19 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0003_remove_caisse_type_caisse_type_operation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='total_grande_caisse',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='total_petite_caisse',
        ),
        migrations.AddField(
            model_name='caisse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caisse',
            name='somme',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
